# Adding workflow rules to avoid other branches to use the pipeline
# since we only want to use the master branch
#workflow:
#  rules:
#    - if: $CI_COMMIT_TAG
#      when: never
#    - if: $CI_COMMIT_BRANCH == 'master'

variables:
  DOCKER_DRIVER: overlay
  IMAGE_OPENJDK_GRADLE: gradle:8.4.0-jdk17-alpine

stages:
  - clean
  - build
  - test
  - build-image
  - publish-image
  - deploy

clean:
  image: $IMAGE_OPENJDK_GRADLE
  stage: clean
  script:
    - echo "cleaning leftovers from previous builds"
    - sh $CI_PROJECT_DIR/gradlew clean


