
name: Java CI with Gradle

on:
  push:
    branches: [ ]
  pull_request:
    branches: [ "main" ]

permissions:
    contents: read

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   - uses: actions/checkout@v4
   - uses: actions/setup-java@v3
     with:
      distribution: 'temurin' # See 'Supported distributions' for available options
      java-version: '17'

   - uses: gradle/gradle-build-action@v2
     with:
        gradle-version: 8.4

   - name:  Build using Gradle
     run:  gradle bootJar --no-daemon

   - name: print build path tree
     run: tree  ./build

   - uses: mr-smithers-excellent/docker-build-push@v6
     name: Build & push Docker image
     with:
       image: bhardwajvarun/ecommerce-product-service
       tags: v1, latest
       registry: docker.io
       dockerfile: src/main/resources/docker/Dockerfile
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_PASSWORD }}
