
name: Java CI with Gradle

on:
  push:
    branches: [ ]
    tags:
      - "*"
  pull_request:
    branches: [ "main" ]

permissions:
    contents: read

jobs:
 build:
  runs-on: self-hosted

  steps:

    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
    - name: Get version
      run: |
        echo "VERSION_NAME=$(${{github.workspace}}/gradlew -q printVersionName --no-daemon)" >> $GITHUB_ENV
    - name: Build version
      run: echo "${{ env.VERSION_NAME }}.${{ github.run_number }}"
    
    - name: Integration Tests
      run: ./gradlew test
    - name: Build Jar
      run: ./gradlew bootJar
    - name: print build path tree
      run: tree  ./build

    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: bhardwajvarun/ecommerce-product-service
        tags: latest, "${{ env.VERSION_NAME }}.${{ github.run_number }}"
        registry: ghcr.io
        dockerfile: src/main/resources/docker/Dockerfile
        username: ${{ secrets.GH_USERNAME }}
        password: ${{ secrets.GH_SECRET_KEY }}
