
name: Java CI with Gradle

on:
  push:
    branches: [ ]
  pull_request:
    branches: [ "main" ]

permissions:
    contents: read

jobs:
 build:
  runs-on: ubuntu-latest

  steps:

    - uses: actions/checkout@v4

    - name: Output Run ID
      run: echo ${{ github.run_id }}
    - name: Output Run Number
      run: echo ${{ github.run_number }}
    - name: Output Run Attempt
      run: echo ${{ github.run_attempt }}
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '17'
    - name: Get version
      run: |
        echo "version_name = $( ${{github.workspace}}/gradlew -q printVersionName --no-daemon)" >> $GITHUB_ENV
        echo ${{env.version_name}}

#   - name:  Build using Gradle
#     run:  gradle bootJar --no-daemon
#
#   - name: print build path tree
#     run: tree  ./build
#
#   - uses: mr-smithers-excellent/docker-build-push@v6
#     name: Build & push Docker image
#     with:
#       image: bhardwajvarun/ecommerce-product-service
#       tags: v1, latest
#       registry: docker.io
#       dockerfile: src/main/resources/docker/Dockerfile
#       username: ${{ secrets.DOCKERHUB_USERNAME }}
#       password: ${{ secrets.DOCKERHUB_PASSWORD }}
