
name: Java CI with Gradle

on:
  push:
    branches: [ ]
  pull_request:
    branches: [ "main" ]

permissions:
    contents: read

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   - uses: actions/checkout@v4
   - uses: actions/setup-java@v3
     with:
      distribution: 'temurin' # See 'Supported distributions' for available options
      java-version: '17'

   - uses: gradle/gradle-build-action@v2
     with:
        gradle-version: 8.4

   - name:  Build using Gradle
     run:  gradle build

   - name: Build and push
     uses: docker/build-push-action@v5
     with:
       push: false
       file: src/main/resources/docker/Dockerfile
       tags: user/app:latest
       secrets: |
         GIT_AUTH_TOKEN=${{ secrets.DOCKER_HUB_TOKEN }}
